<?php /** @noinspection PhpUndefinedVariableInspection */

/***************************************************************
 * Extension Manager/Repository config file for ext: "phlbootstrapextend"
 *
 * Auto generated by Extension Builder 2019-05-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'phlbootstrap_extend',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christian Platt',
    'author_email' => 'christian.platt@pharmaline.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.9',
    'constraints' => [
            'depends' => [
                'typo3' => '9.5.0-9.5.99',
            ],
            'conflicts' => [],
            'suggests' => [],
    ],
];
